# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # optional
          # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # optional
          # AWS Session Token
          aws-region: eu-south-1

      - uses: pearljobs/chrome-aws-lambda-layer-action@v1
        with:
          repoOwner: alixaxel
          repo: chrome-aws-lambda
          regions: us-west-1,us-west-2,us-east-1,us-east-2,eu-south-1
          bucketPrefix: 'static-files-'
          commit: true
          description: |+
            Lambda layers automatically deployed from [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) builds.

            This repo checks for changes weekly so if you need a release sooner, open an issue and I'll trigger a workflow run.

            Similarly if this doesn't currently deploy to a region you need, open an issue and I'll add it
      - uses: EndBug/add-and-commit@v7.4.0
        with:
          # Arguments for the git add command
          add: README.md

            
